---
title: 'Impacto do Pronaf B na Taxa de Crescimento dos Municípios Cearenses'
date: "`r paste(tools::toTitleCase(format(Sys.Date(), '%B')), format(Sys.Date(), 'de %Y'))`"
author: "Alysson Inácio de Oliveira"
place: "Fortaleza"
institution: "Universidade de Fortaleza - UNIFOR"
curso: 'Ciências econômicas'
centro: 'Centro de Ciências da Comunicação e Gestão - CCG'
orientador: "Prof. Dr. Nicolino Trompieri Neto"
desc_orientador: 'Orientador'
professor_convidado1: "Professor Convidado" 
desc_prof_convidado1: 'Convidado 1'
professor_convidado2: 'Professor'
desc_prof_convidado2: 'Convidado 2'
img_capa: img/unifor.png

preamble: 'Monografia apresentada ao Curso de Graduação em Ciências Econômicas da Universidade de Fortaleza - UNIFOR, como requisito parcial à obtenção do título de Graduação em Ciências Econômicas.'

# Agradecimentos

agradecimentos: agradecimentos/agradecimentos.tex
base-header-level: 1
base-numbering-level: 1


# Resumo e palavras-chave do trabalho

resumo: abstracts/resumo.tex
tags_resumo: economia, avaliação de impactos
abstract: abstracts/abstract.tex
tags_abstract: economic, avaliação de impactos
JEL: J45, C45, G45
key-word1: Palavra-chave1
key-word2: Palavra-chave2
key-word3: Palavra-chave3


# Informações do output

output:
  pdf_document:
    keep_tex: true
    template: rmarkdown-templates/abntex2_template.tex
    fig_caption: true
    
# Informações do documento

documentclass: abntex2
fontsize: 12pt
papersize: a4paper
lang: english, french, spanish, brazil
mainlang: brazil
classoption: twoside, openright
linkcolor: blue
capa: true
folhaderosto: true
tipotrabalho: Monografia (Graduação)
biblatex: yes
bibliography: bib/bibliografia.bib  
csl: bib/associacao-brasileira-de-normas-tecnicas-ipea.csl
toc: yes
MakeUppercase: true # para letras maiúsculas
family: lmodern

# Elementos pós-aprovação

fichacatalografica: false
local_fichacatalografica: pos_text/fichacatalografica.pdf

folhadeaprovacao: false
local_folhadeaprovacao: pos_text/folhadeaprovacao.pdf

# Inclui no Sumário o capítulo de referência sem a numeração.

contents-references: yes
references-name: "REFERÊNCIAS"
---

<!-- Configuração Geral dos chunks -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```


<!-- Incício do Documento -->


\chapter{Introdução}

```{r, child='chapters/chapter1.Rmd'}

```

\chapter{Referencial Teórico}

\chapter{Metodologia}

\chapter{Resultados}

\chapter{Conclusão}

\postextual

\chapter*{Referências}
\setlength{\parindent}{0cm}







